
package com.todoservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TodoListInterfaceService", targetNamespace = "http://www.todoservices.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TodoListInterfaceService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.LoginResponse")
    @Action(input = "http://www.todoservices.com/TodoListInterfaceService/loginRequest", output = "http://www.todoservices.com/TodoListInterfaceService/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listUsers", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.ListUsers")
    @ResponseWrapper(localName = "listUsersResponse", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.ListUsersResponse")
    @Action(input = "http://www.todoservices.com/TodoListInterfaceService/listUsersRequest", output = "http://www.todoservices.com/TodoListInterfaceService/listUsersResponse")
    public String listUsers();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addTodo", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.AddTodo")
    @ResponseWrapper(localName = "addTodoResponse", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.AddTodoResponse")
    @Action(input = "http://www.todoservices.com/TodoListInterfaceService/addTodoRequest", output = "http://www.todoservices.com/TodoListInterfaceService/addTodoResponse")
    public String addTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryTodos", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.QueryTodos")
    @ResponseWrapper(localName = "queryTodosResponse", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.QueryTodosResponse")
    @Action(input = "http://www.todoservices.com/TodoListInterfaceService/queryTodosRequest", output = "http://www.todoservices.com/TodoListInterfaceService/queryTodosResponse")
    public String queryTodos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteTodo", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.DeleteTodo")
    @ResponseWrapper(localName = "deleteTodoResponse", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.DeleteTodoResponse")
    @Action(input = "http://www.todoservices.com/TodoListInterfaceService/deleteTodoRequest", output = "http://www.todoservices.com/TodoListInterfaceService/deleteTodoResponse")
    public String deleteTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "clearTodo", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.ClearTodo")
    @ResponseWrapper(localName = "clearTodoResponse", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.ClearTodoResponse")
    @Action(input = "http://www.todoservices.com/TodoListInterfaceService/clearTodoRequest", output = "http://www.todoservices.com/TodoListInterfaceService/clearTodoResponse")
    public String clearTodo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://www.todoservices.com", className = "com.todoservices.RegisterResponse")
    @Action(input = "http://www.todoservices.com/TodoListInterfaceService/registerRequest", output = "http://www.todoservices.com/TodoListInterfaceService/registerResponse")
    public String register(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
